# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a99d701e7f9a519f21c7ea16a5501d110b1bae1206319e41c3531f8f99386bcbcffc6616319c0e1a5eee8486cbb8418072c715e57a5733dd231583571211aeb8

test:
  secret_key_base: 86633c09df37fdd6295f4bb4ef894fb62dcf6cdc15ccb477b58021ba5175e115ec32bbe87a8b6afb5194de141d27b7eb70ba467a3d0a6985cbd15dbc544b096d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
